config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'welcome#index'
  get 'welcome/index'
resources :posts do
  resources :likes
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  has_many :likes, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	  before_action :find_post 
	  before_action :find_like, only: [:destroy]

	  def create
          if already_liked?
                flash[:notice] = "You can't like more than once"
               else
                @post.likes.create(user_id: current_user.id)
           end
            redirect_to post_path(@post)
       end 


      def already_liked?
         Like.where(user_id: current_user.id, post_id:
         params[:post_id]).exists?
      end

      def destroy
         if !(already_liked?)
                flash[:notice] = "Cannot unlike"
             else
                @like.destroy
         end
             redirect_to post_path(@post)
      end

      def find_like
         @like = @post.likes.find(params[:id])
      end

      private  
      def find_post
       @post = Post.find(params[:post_id])
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all

    end
  def new
  	@post = Post.new
  end

  def create
  	@post = Post.create(user_params)
  	redirect_to posts_path
  end

  def show
  	@post = Post.find(params[:id])
  end

  def edit
  end

  def user_params
  	params.require(:post).permit(:title,:body,:user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LikeUserPostDevise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <%=link_to'Posts',posts_path%>
<% else %>
<br>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <%end%>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<table border=1>
	<tr>
	  <th>Post_Title</th>
	  <th>Post_Body</th>
	   <th>User_Id</th>
	    <th>Post_Id</th>
	    <th>Likes</th>
	    <th>ShowPost</th>
    </tr>
    <%@posts.each do |var|%>
       <tr>
          <td><%=var.title%></td>
          <td><%=var.body%></td>
          <td><%=var.user_id%></td>
          <td><%=var.id%></td>
          <td><p><%= var.likes.count %> <%= (var.likes.count) == 1 ? 'Like' : 'Likes'%></p></td>
          <td><%=link_to'show',post_path(var.id)%></td>
      </tr>
    <%end%>
</table>
<%=link_to 'New_Post',new_post_path%>

app/views/posts/new.html.erb
<h1>Posts#new</h1>

<%=form_for @post do |f|%>

<%=f.label'UserId'%>
<%=f.text_field :user_id%><br>

<%=f.label'Title'%>
<%=f.text_field :title%><br>

<%=f.label'Body'%>
<%=f.text_area :body%><br>

<%=f.submit%><br>
<%end%>

app/views/posts/show.html.erb
<h1>Posts#show</h1>

<table border=1>
	<tr>
	  <th>Post_Title</th>
	  <th>Post_Body</th>
	   <th>User_Id</th>
	    <th>Post_Id</th>
	    <th>Likes</th>
    </tr>
   
       <tr>
          <td><%=@post.title%></td>
          <td><%=@post.body%></td>
           <td><%=@post.user_id%></td>
            <td><%=@post.id%></td>
            <td><p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p></td>

      </tr>
   
</table>
<%=link_to 'Back',root_path%><br>
 

  <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
   <% if pre_like %>
         <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
     <% else %>
         <%= button_to 'Like', post_likes_path(@post), method: :post %>
   <% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>